### PR TITLE
Add support of custom envvars

### PR DESCRIPTION
**Pull request by fur-gan**

### CODE REVIEW

**Comment by DmitryAstafyev** [comment]
If we have some table view, which would be scrollable in the vertical direction, we should take care of the stuck header. I mean header always should be on the top.

Also, I think it better to use "Value" instead "Path".

Screenshot 2021-03-17 at 18 48 45

**Comment by DmitryAstafyev** [comment]
The idea of adding a new variable into the list directly - very nice. Here are a couple of suggestions:
- add to the bottom, but not to the top
- if a user isn't at the top of the list - scroll it to the bottom with click on "Add"
- and "Create" better rename to "Add"

**Comment by DmitryAstafyev** [comment]
I think we don't need horizontal scrolling. The left column can have a fixed width and the right column can always fit to the width of the dialog.
Screenshot 2021-03-17 at 18 49 49

**Comment by DmitryAstafyev** [comment]
Without white border it looks better. Isn't?

Screenshot 2021-03-17 at 18 53 52

**Comment by DmitryAstafyev** [comment]
Broken views:

Screenshot 2021-03-17 at 18 50 46

Screenshot 2021-03-17 at 19 03 44

**Comment by DmitryAstafyev** [comment]
About icons

Screenshot 2021-03-17 at 19 05 39

**Comment by marcmo** [comment]
looks all good!

**Pull request merged**
